export CUDA_VISIBLE_DEVICES=2

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate wsol_histology

#python main.py --task STD_CL --encoder_name resnet50 --pixel_wise_classification True --path_cam resnet50-gradcampp-bloc-camelyon --path_pre_trained_model_cl CAMELYON512-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.1 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial True --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 1 --sl_max 1 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling WGAP --dataset CAMELYON512 --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --exp_id source_6_CAMELYON512_EnergyCAM_gradcampp_px1 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res False &


python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification False --runmode search-mode --opt__name_optimizer sgd --batch_size 128 --eval_batch_size 256 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.9 --max_epochs 50 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method DEEPMIL --mil_gated True --spatial_pooling DeepMil --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.0000001 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type best_classification --sf_uda_source_wsol_method DEEPMIL --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --esfda True --esfda_select_imgs True --esfda_select_imgs_ratio 0.1 --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.1 --target_domain_ds_to_compute_stats GLAS --ds_to_compute_acc_trainset_source_target GLAS --cmpt_batch 10 --cl_train_models True --exp_id test_unlearning_notfreeze_correct_incorrect_GLAS_DEEPMIL_01 &
python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification False --runmode search-mode --opt__name_optimizer sgd --batch_size 128 --eval_batch_size 256 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.9 --max_epochs 50 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method DEEPMIL --mil_gated True --spatial_pooling DeepMil --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.000001 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type best_classification --sf_uda_source_wsol_method DEEPMIL --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --esfda True --esfda_select_imgs True --esfda_select_imgs_ratio 0.1 --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.1 --target_domain_ds_to_compute_stats GLAS --ds_to_compute_acc_trainset_source_target GLAS --cmpt_batch 10 --cl_train_models True --exp_id test_unlearning_notffreeze_correct_incorrect_GLAS_DEEPMIL_02 &
python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification False --runmode search-mode --opt__name_optimizer sgd --batch_size 128 --eval_batch_size 256 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.9 --max_epochs 50 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method DEEPMIL --mil_gated True --spatial_pooling DeepMil --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.00001 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type best_classification --sf_uda_source_wsol_method DEEPMIL --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --esfda True --esfda_select_imgs True --esfda_select_imgs_ratio 0.1 --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.1 --target_domain_ds_to_compute_stats GLAS --ds_to_compute_acc_trainset_source_target GLAS --cmpt_batch 10 --cl_train_models True --exp_id test_unlearning_notffreeze_correct_incorrect_GLAS_DEEPMIL_03 &
python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification False --runmode search-mode --opt__name_optimizer sgd --batch_size 128 --eval_batch_size 256 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.9 --max_epochs 50 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method DEEPMIL --mil_gated True --spatial_pooling DeepMil --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type best_classification --sf_uda_source_wsol_method DEEPMIL --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --esfda True --esfda_select_imgs True --esfda_select_imgs_ratio 0.1 --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.1 --target_domain_ds_to_compute_stats GLAS --ds_to_compute_acc_trainset_source_target GLAS --cmpt_batch 10 --cl_train_models True --exp_id test_unlearning_notffreeze_correct_incorrect_GLAS_DEEPMIL_04 &
#python main.py -- main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification False --runmode search-mode --opt__name_optimizer sgd --batch_size 128 --eval_batch_size 256 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.9 --max_epochs 50 --freeze_classifier_sfda True --freeze_encoder_sfda False --support_background False --method DEEPMIL --mil_gated True --spatial_pooling DeepMil --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type best_classification --sf_uda_source_wsol_method DEEPMIL --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --esfda True --esfda_select_imgs True --esfda_select_imgs_ratio 0.1 --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.1 --target_domain_ds_to_compute_stats GLAS --ds_to_compute_acc_trainset_source_target GLAS --cmpt_batch 10 --cl_train_models True --exp_id test_unlearning_correct_incorrect_GLAS_DEEPMIL_05 &

wait
