export CUDA_VISIBLE_DEVICES=0

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate SFDA_env_wsol_histology_clone

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 1 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 2 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 3 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 4 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 5 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 6 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 7 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 8 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 9 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 10 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

# python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 11 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 



python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 1 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 2 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 3 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 4 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 5 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 6 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 7 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 8 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 9 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 10 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 

python get_accuracy_models.py --cudaid 0 --split test --checkpoint_type best_classification --encoder_name deit_sat_tiny_patch16_224 --sfda_method sfde --source_dataset EBHI --fold_source_dataset 0 --target_dataset EBHI --fold_target_dataset 11 --output_dir /export/livia/home/vision/Aguichemerre/iclr_2027_results --wsol_method gradcampp --umap_max_images_per_class 500 --umap_n_neighbors 15 --umap_min_dist 0.2 --umap_metric cosine --plot_tedloc_pixel_entropy True --path_pre_trained_source /export/livia/home/vision/Aguichemerre/src_models_ICLR_2027/id_source_3_EBHI_SAT_sat_low_res_100-tsk_STD_CL-ds_EBHI-fold_0-mag_None-runmode_search-mode-mth_SAT-spooling_GAP-arch_SATClassifier-ecd_deit_sat_tiny_patch16_224 



wait