export CUDA_VISIBLE_DEVICES=1

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate SFDA_env_wsol_histology


python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification True --runmode search-mode --opt__name_optimizer sgd --batch_size 64 --eval_batch_size 32 --eval_checkpoint_type B-UNLEARNING_valpx --opt__step_size 5 --opt__gamma 0.9 --max_epochs 10 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method PixelCAM --mil_gated True --spatial_pooling DeepMil --dataset CAMELYON17_512 --fold 3 --debug_subfolder None --amp True --opt__lr 0.0001 --opt__weight_decay 1e-4 --sf_uda True --sf_uda_source_ds CAMELYON17_512 --sf_uda_source_ds_fold 3 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type B-UNLEARNING_valcl --sf_uda_source_wsol_method PixelCAM --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --grsfda False --esfda False --esfda_select_imgs True --esfda_select_imgs_ratio 0.15 --retain_all_others True --dynamic_selection True --resample_every 2 --measure_loc False --save_multiple_unlearn_models False --ce_pseudo_lb False --balance_stable_to_flips False --stable_match_strategy True --entropy_probabilistic False --entropy_gt False --entropy_random False --select_distance False --select_entropy True --random_select_ratio 1.0 --esfda_reverse_imgs True --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.01 --esfda_weight_entropy linear --esfda_flip_labels False --CEForget_lambda 1.0 --esfda_notflip_labels False --CERetain_lambda 1.0 --esfda_flip_labels_weight False --esfda_loc False --esfda_loc_lambda 1.0 --esfda_loc_mode mse --ece False --ece_lambda 5.0 --epx False --epx_lambda 0.5 --forget_el False --forget_lambda 5.0 --sl_min 100 --sl_max 100 --sl_min_p 0.6 --low_res True --crf_fc False --crf_lambda 1e-4 --crf_sigma_xy 10 --sl_pc_seeder probability_negative_salloarea_seeder --unlearning_models True --m_unlearning_models 1 --fold_came_compute 0 --cmpt_batch 1000 --cl_train_models False --sfde False --cdd_lambda 0.01 --sfde_threshold 1 --cdd_pseudo_lb False --cdcl True --cdcl_threshold 1.0 --cdcl_cvg 0.001 --cdcl_pseudo_lb True --cdcl_tau 1.0 --cdcl_lambda 1.0 --ece_adapt True --ece_adapt_lambda 1.0 --entropy_filter_mode True --keep_ratio 0.3 --neg_samples_partial True --exp_id sfda_c17_100_filtered_1p0_b64_full_res &


wait
