export CUDA_VISIBLE_DEVICES=2

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate SFDA_env_wsol_histology

python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification True --runmode search-mode --opt__name_optimizer sgd --batch_size 32 --eval_batch_size 32 --eval_checkpoint_type B-UNLEARNING_valpx --opt__step_size 5 --opt__gamma 0.9 --max_epochs 15 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method PixelCAM --mil_gated True --spatial_pooling DeepMil --dataset CAMELYON512 --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --opt__weight_decay 1e-4 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type B-UNLEARNING_valcl --sf_uda_source_wsol_method PixelCAM --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --sl_min 10 --sl_max 10 --sl_min_p 0.6 --low_res True --crf_fc False --crf_lambda 1e-4 --crf_sigma_xy 10 --sl_pc_seeder probability_negative_salloarea_seeder --sfde True --cdd_lambda 1.0 --sfde_threshold 1.0 --cdd_pseudo_lb True --ece_adapt True --ece_adapt_lambda 0.2 --neg_samples_partial True --rgv False --sfda_aug_transform False --ce_pseudo_lb False --ce_pseudo_lb_lambda 0.4 --div_pseudo_lb False --div_pseudo_lb_lambda 0.4 --semalg False --lambdaS 0.4 --betaS 0.7 --exp_id sfde_deepmil_unlearn_c16 &


python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification True --runmode search-mode --opt__name_optimizer sgd --batch_size 32 --eval_batch_size 32 --eval_checkpoint_type B-UNLEARNING_valpx --opt__step_size 5 --opt__gamma 0.9 --max_epochs 15 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method PixelCAM --mil_gated True --spatial_pooling DeepMil --dataset CAMELYON512 --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --opt__weight_decay 1e-4 --sf_uda True --sf_uda_source_ds CAMELYON512 --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type B-UNLEARNING_valcl --sf_uda_source_wsol_method PixelCAM --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --sl_min 10 --sl_max 10 --sl_min_p 0.6 --low_res True --crf_fc False --crf_lambda 1e-4 --crf_sigma_xy 10 --sl_pc_seeder probability_negative_salloarea_seeder --sfde False --cdd_lambda 1.0 --sfde_threshold 1.0 --cdd_pseudo_lb False --ece_adapt True --ece_adapt_lambda 0.2 --neg_samples_partial True --rgv True --sfda_aug_transform True --ce_pseudo_lb True --ce_pseudo_lb_lambda 0.5 --div_pseudo_lb True --div_pseudo_lb_lambda 1.0 --semalg True --lambdaS 0.4 --betaS 0.7 --exp_id rgv_deepmil_unlearn_c16 &

wait
