export CUDA_VISIBLE_DEVICES=1

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate SFDA_env_wsol_histology

python main.py --task STD_CL --encoder_name resnet50 --arch STDClassifier --pixel_wise_classification False --runmode search-mode --opt__name_optimizer sgd --batch_size 32 --eval_batch_size 32 --eval_checkpoint_type best_localization --opt__step_size 5 --opt__gamma 0.9 --max_epochs 100 --freeze_classifier_sfda False --freeze_encoder_sfda False --support_background False --method DEEPMIL --mil_gated True --spatial_pooling DeepMil --dataset CAMELYON17_512 --fold 4 --debug_subfolder None --amp True --opt__lr 0.00001 --opt__weight_decay 1e-4 --sf_uda True --sf_uda_source_ds GLAS --sf_uda_source_ds_fold 0 --sf_uda_source_encoder_name resnet50 --sf_uda_source_checkpoint_type best_classification --sf_uda_source_wsol_method DEEPMIL --sf_uda_source_wsol_arch STDClassifier --sf_uda_source_wsol_spatial_pooling DeepMil --grsfda False --esfda True --esfda_select_imgs True --esfda_select_imgs_ratio 0.1 --retain_all_others True --dynamic_selection True --resample_every 10 --save_multiple_unlearn_models True --ce_pseudo_lb False --balance_stable_to_flips False --stable_match_strategy True --entropy_probabilistic False --entropy_gt False --entropy_random False --select_distance False --select_entropy True --random_select_ratio 1.0 --esfda_reverse_imgs True --esfda_entropy_partial True --esfda_entropy_partial_lambda 0.01 --esfda_weight_entropy linear --esfda_flip_labels True --CEForget_lambda 0.5 --esfda_notflip_labels True --CERetain_lambda 1.0 --esfda_flip_labels_weight False --esfda_loc False --esfda_loc_lambda 1.0 --esfda_loc_mode mse --ece_adapt False --ece_adapt_lambda 1.0 --sl_min 30 --sl_max 30 --sl_min_p 0.2 --neg_samples_partial False --low_res True --sl_pc_seeder probability_negative_salloarea_seeder --path_cam resnet50-deepmil-bcl-glas-camelyon17512_4 --unlearning_models True --m_unlearning_models 1 --target_domain_ds_to_compute_stats CAMELYON17_512 --ds_to_compute_acc_trainset_source_target GLAS --fold_came_compute 4 --cmpt_batch 120 --cl_train_models True --sfde False --cdd_lambda 0.01 --sfde_threshold 1 --cdd_pseudo_lb False --exp_id unlearning_c17_4_100 

wait
