export CUDA_VISIBLE_DEVICES=2

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate wsol_histology

python main.py --task NEGEV --encoder_name resnet50 --arch UnetNEGEV --runmode search-mode --opt__name_optimizer sgd --batch_size 32 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.1 --opt__lr 0.0001 --max_epochs 1000 --freeze_cl True --support_background True --method LayerCAM --spatial_pooling WGAP --mil_gated False --dataset GLAS --fold 0 --debug_subfolder None --amp True --negev_ptretrained_cl_cp best_classification --elb_init_t 1.0 --elb_max_t 10.0 --elb_mulcoef 1.01 --sl_ng True --sl_ng_seeder probability_seeder --sl_ng_lambda 1.0 --sl_ng_start_ep 0 --sl_ng_end_ep -1 --sl_ng_min 5 --sl_min 5 --sl_max 5 --sl_ng_max 5 --sl_ng_ksz 3 --crf_ng False --jcrf_ng False --neg_samples_ng False --max_sizepos_ng False --exp_id NEGEV_glas_layercam_4 &
python main.py --task NEGEV --encoder_name resnet50 --arch UnetNEGEV --runmode search-mode --opt__name_optimizer sgd --batch_size 32 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.1 --opt__lr 0.001 --max_epochs 1000 --freeze_cl True --support_background True --method LayerCAM --spatial_pooling WGAP --mil_gated False --dataset GLAS --fold 0 --debug_subfolder None --amp True --negev_ptretrained_cl_cp best_classification --elb_init_t 1.0 --elb_max_t 10.0 --elb_mulcoef 1.01 --sl_ng True --sl_ng_seeder probability_seeder --sl_ng_lambda 1.0 --sl_ng_start_ep 0 --sl_ng_end_ep -1 --sl_ng_min 5 --sl_min 5 --sl_max 5 --sl_ng_max 5 --sl_ng_ksz 3 --crf_ng False --jcrf_ng False --neg_samples_ng False --max_sizepos_ng False --exp_id NEGEV_glas_layercam_5 &
python main.py --task NEGEV --encoder_name resnet50 --arch UnetNEGEV --runmode search-mode --opt__name_optimizer sgd --batch_size 32 --eval_checkpoint_type best_localization --opt__step_size 250 --opt__gamma 0.1 --opt__lr 0.01 --max_epochs 1000 --freeze_cl True --support_background True --method LayerCAM --spatial_pooling WGAP --mil_gated False --dataset GLAS --fold 0 --debug_subfolder None --amp True --negev_ptretrained_cl_cp best_classification --elb_init_t 1.0 --elb_max_t 10.0 --elb_mulcoef 1.01 --sl_ng True --sl_ng_seeder probability_seeder --sl_ng_lambda 1.0 --sl_ng_start_ep 0 --sl_ng_end_ep -1 --sl_ng_min 5 --sl_min 5 --sl_max 5 --sl_ng_max 5 --sl_ng_ksz 3 --crf_ng False --jcrf_ng False --neg_samples_ng False --max_sizepos_ng False --exp_id NEGEV_glas_layercam_6 &

wait