export CUDA_VISIBLE_DEVICES=0

source /export/livia/home/vision/Aguichemerre/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda activate wsol_histology

python main.py --task STD_CL --encoder_name resnet50 --pixel_wise_classification True --path_cam resnet50-gradcampp-bloc-glas --path_pre_trained_model_cl GLAS-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.9 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial False --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 10 --sl_max 10 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling WGAP --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --exp_id source_0_GLAS_EnergyCAM_gradcampp_px10 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res False &
python main.py --task STD_CL --encoder_name resnet50 --pixel_wise_classification True --path_cam resnet50-gradcampp-bloc-glas --path_pre_trained_model_cl GLAS-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.9 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial False --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 10 --sl_max 10 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling WGAP --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.001 --exp_id source_1_GLAS_EnergyCAM_gradcampp_px10 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res False &
python main.py --task STD_CL --encoder_name resnet50 --pixel_wise_classification True --path_cam resnet50-gradcampp-bloc-glas --path_pre_trained_model_cl GLAS-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.9 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial False --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 10 --sl_max 10 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling WGAP --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.01 --exp_id source_2_GLAS_EnergyCAM_gradcampp_px10 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res False &

python main.py --task STD_CL --encoder_name resnet50 --pixel_wise_classification True --path_cam resnet50-gradcampp-bloc-glas --path_pre_trained_model_cl GLAS-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.4 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial False --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 10 --sl_max 10 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling WGAP --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.0001 --exp_id source_3_GLAS_EnergyCAM_gradcampp_px10 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res False &
python main.py --task STD_CL --encoder_name resnet50 --pixel_wise_classification True --path_cam resnet50-gradcampp-bloc-glas --path_pre_trained_model_cl GLAS-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.4 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial False --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 10 --sl_max 10 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling WGAP --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.001 --exp_id source_4_GLAS_EnergyCAM_gradcampp_px10 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res False &
#python main.py --task STD_CL --encoder_name deit_sat_tiny_patch16_224 --pixel_wise_classification True --path_cam deit_satcam_tiny_patch16_224-sat-bloc-glas --path_pre_trained_model_cl GLAS-0-resnet50-GradCAMpp-WGAP-cp_best_classification --arch STDClassifier --runmode search-mode --opt__name_optimizer sgd --eval_batch_size 128 --batch_size 32 --eval_checkpoint_type best_localization --opt__lr_classifier_ratio 10.0 --opt__step_size 5 --opt__gamma 0.4 --max_epochs 20 --freeze_cl False --support_background True --method EnergyCAM --image_classifier True --ece True --ece_lambda 1.0 --pxortho False --pxortho_lambda 1.0 --neg_samples_partial False --neg_samples_ng False --neg_samples_ng_lambda 0.4 --sl_pc_seeder probability_negative_salloarea_seeder --sl_min 10 --sl_max 10 --sl_min_p 0.4 --entropy_fc False --entropy_fc_lambda 1.0 --elb_init_t 3. --elb_max_t 10. --elb_mulcoef 1.01 --max_sizepos_fc False --max_sizepos_fc_lambda 0.1 --max_sizepos_fc_start_ep 0 --max_sizepos_fc_end_ep -1 --crf_fc False --crf_lambda 2e-09 --crf_sigma_rgb 2.0 --crf_sigma_xy 100.0 --crf_scale 1.0 --crf_start_ep 0 --crf_end_ep -1 --mil_gated False --spatial_pooling GAP --dataset GLAS --fold 0 --debug_subfolder None --amp True --opt__lr 0.01 --exp_id source_5_GLAS_EnergyCAM_gradcampp_px10 --batch_norm False --multiple_layer False --anchors_ortogonal False --detach_pixel_classifier False --low_res True &


wait
